(()=>{
const VERSION='V7.3.5';
let finance=null,chatBusy=false;
const yen=n=>Number.isFinite(Number(n))?'¥'+Number(n).toLocaleString('ja-JP'):'—';
const dateParts=()=>{const p=new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',year:'numeric',month:'numeric',day:'numeric'}).formatToParts(new Date());const o=Object.fromEntries(p.map(x=>[x.type,x.value]));return{y:+o.year,m:+o.month,d:+o.day}};
const cutoff=()=>{const d=finance?.actualsCutoff||finance?.latestActualDate;if(!d)return'確認日時点';const m=String(d).match(/(?:\d{4}-)?(\d{1,2})-(\d{1,2})$/);return m?`${Number(m[1])}/${Number(m[2])}時点`:'確認日時点'};
function css(){if(document.getElementById('ups-home-v735-style'))return;const s=document.createElement('style');s.id='ups-home-v735-style';s.textContent=`
#aiOffice{position:relative;isolation:isolate;overflow:hidden;min-height:100%;padding:18px 14px 22px;border:1px solid rgba(32,203,255,.22);border-radius:26px;background:radial-gradient(circle at 50% 31%,rgba(0,139,200,.22),transparent 30%),linear-gradient(180deg,#031523 0%,#02101b 58%,#010913 100%);box-shadow:inset 0 0 90px rgba(0,190,255,.06),0 22px 70px rgba(0,0,0,.36);color:#effcff}
#aiOffice:before{content:"";position:absolute;inset:0;z-index:-1;background:linear-gradient(rgba(35,218,255,.035) 1px,transparent 1px),linear-gradient(90deg,rgba(35,218,255,.035) 1px,transparent 1px);background-size:34px 34px;mask-image:linear-gradient(to bottom,#000,transparent 70%)}
.ups-head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px}.ups-logo{font-weight:950;font-size:28px;letter-spacing:.17em;line-height:.9}.ups-logo em{font-style:normal;color:#22e0ff}.ups-logo small{display:block;margin-top:8px;font-size:10px;letter-spacing:.34em;color:#cceffc}.ups-icons{display:flex;gap:8px}.ups-icon{width:40px;height:40px;border:1px solid rgba(52,214,255,.28);border-radius:13px;display:grid;place-items:center;background:#041827;color:#dffaff;font-size:18px}
.ups-greet{margin-top:28px}.ups-greet .hello{font-size:23px;font-weight:700}.ups-greet h1{font-size:42px;line-height:1.03;margin:5px 0 8px;letter-spacing:.01em}.ups-greet p{margin:0;color:#a9cad5;font-size:13px;line-height:1.7}.ups-month{display:inline-flex;align-items:center;gap:7px;margin-top:15px;padding:9px 13px;border:1px solid rgba(42,196,255,.3);border-radius:999px;background:#041a2a;color:#e6fbff;font-size:13px;font-weight:800}
.ups-core-zone{position:relative;display:grid;place-items:center;min-height:385px;margin-top:4px}.ups-orbit{position:absolute;width:330px;height:330px;border-radius:50%;border:1px solid rgba(42,213,255,.22);box-shadow:0 0 70px rgba(0,192,255,.08),inset 0 0 45px rgba(0,192,255,.06)}.ups-orbit:before,.ups-orbit:after{content:"";position:absolute;border-radius:50%;inset:20px;border:1px dashed rgba(50,217,255,.20)}.ups-orbit:after{inset:54px;border-style:solid;opacity:.6}.ups-sweep{position:absolute;inset:0;border-radius:50%;background:conic-gradient(from 0deg,transparent 0 305deg,rgba(49,231,255,.06) 325deg,rgba(73,237,255,.42) 360deg);animation:upsSweep 7s linear infinite}.ups-core{position:relative;z-index:3;width:190px;height:190px;border-radius:50%;border:1px solid #65ecff;background:radial-gradient(circle at 50% 34%,#b9fbff 0 3%,#23d9ff 4% 8%,#0a6582 9% 24%,#042637 25% 54%,#01090f 55% 100%);box-shadow:0 0 24px rgba(162,249,255,.6),0 0 70px rgba(23,213,255,.42),inset 0 0 40px rgba(57,224,255,.18);color:#fff;display:grid;place-items:center;text-align:center;cursor:pointer;animation:upsPulse 2.4s ease-in-out infinite}.ups-core.busy{animation:upsBusy .7s ease-in-out infinite alternate}.ups-core b{font-size:24px;letter-spacing:.14em}.ups-core small{display:block;margin-top:8px;color:#79e8ff;font-size:10px;letter-spacing:.18em}.ups-wave{margin:8px auto 0;width:70px;height:22px;background:repeating-linear-gradient(90deg,#35e7ff 0 3px,transparent 3px 7px);clip-path:polygon(0 42%,6% 38%,10% 55%,15% 27%,20% 70%,25% 12%,30% 82%,35% 24%,40% 68%,46% 8%,52% 90%,58% 20%,64% 69%,70% 34%,76% 60%,82% 39%,88% 54%,94% 44%,100% 48%,100% 58%,94% 56%,88% 66%,82% 54%,76% 73%,70% 45%,64% 80%,58% 34%,52% 96%,46% 18%,40% 77%,35% 35%,30% 89%,25% 25%,20% 76%,15% 40%,10% 64%,6% 48%,0 54%)}
.ups-talk{position:absolute;z-index:4;bottom:8px;display:flex;align-items:center;justify-content:center;gap:11px;min-width:min(88%,390px);padding:14px 20px;border:1px solid #3ce2ff;border-radius:999px;background:linear-gradient(180deg,#07528a,#05355e);box-shadow:0 0 24px rgba(18,213,255,.3),inset 0 0 22px rgba(85,230,255,.1);color:#efffff;font-weight:900;cursor:pointer}.ups-talk span{font-size:24px}.ups-talk small{display:block;color:#60e8ff;font-size:10px;margin-top:2px;font-weight:700}
.ups-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin-top:20px}.ups-kpi{padding:12px 10px;border:1px solid rgba(44,203,255,.24);border-radius:15px;background:linear-gradient(180deg,rgba(4,39,61,.92),rgba(2,20,34,.92));min-height:96px}.ups-kpi span{display:block;font-size:10px;color:#76dff2;font-weight:850}.ups-kpi b{display:block;margin-top:8px;font-size:17px}.ups-kpi small{display:block;margin-top:5px;color:#86aab5;font-size:9px}.ups-kpi.gross{border-color:rgba(45,231,169,.30)}.ups-kpi.gross span{color:#57f0bd}.ups-kpi.dr{border-color:rgba(166,108,255,.30)}.ups-kpi.dr span{color:#bd91ff}.ups-kpi.today{border-color:rgba(255,178,75,.32)}.ups-kpi.today span{color:#ffc063}
.ups-menu{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px;margin-top:16px}.ups-menu button{min-height:78px;padding:12px;border:1px solid rgba(38,195,246,.28);border-radius:16px;background:#032033;color:#ecfbff;text-align:left;cursor:pointer}.ups-menu b{display:block;font-size:13px}.ups-menu small{display:block;margin-top:5px;color:#87aeba;font-size:9px;line-height:1.4}.ups-menu .ico{font-size:20px;margin-bottom:7px;color:#51ddff}.ups-note{margin-top:13px;padding:10px 12px;border:1px solid rgba(255,180,66,.18);border-radius:12px;background:rgba(58,33,8,.58);color:#eecb97;font-size:10px;line-height:1.55}.ups-footer{display:flex;justify-content:space-between;gap:8px;margin-top:12px;color:#3d8598;font-size:8px;letter-spacing:.08em}
@keyframes upsSweep{to{transform:rotate(360deg)}}@keyframes upsPulse{50%{transform:scale(1.035);filter:brightness(1.12)}}@keyframes upsBusy{to{transform:scale(1.06);filter:brightness(1.35)}}
@media(max-width:640px){#aiOffice{padding:16px 12px 18px;border-radius:22px}.ups-logo{font-size:23px}.ups-greet{margin-top:22px}.ups-greet .hello{font-size:19px}.ups-greet h1{font-size:38px}.ups-greet p{font-size:12px}.ups-core-zone{min-height:350px}.ups-orbit{width:290px;height:290px}.ups-core{width:164px;height:164px}.ups-core b{font-size:21px}.ups-kpis{grid-template-columns:1fr 1fr}.ups-kpi{min-height:88px}.ups-menu{grid-template-columns:1fr 1fr}.ups-menu button{min-height:74px}.ups-talk{bottom:0}.ups-footer{font-size:7px}}
`;document.head.appendChild(s)}
function hideLegacy(){const home=document.getElementById('home');if(home){[...home.children].forEach(el=>{if(el.id!=='aiOffice')el.style.display='none'})}const old=document.getElementById('voiceCore');if(old){const wrap=old.closest('.core-wrap,.corebox');if(wrap)wrap.style.display='none'}document.querySelectorAll('.nav [data-go="ai"],.dock [data-go="ai"]').forEach(b=>b.style.display='none');const dock=document.querySelector('.dock');if(dock)dock.style.gridTemplateColumns='repeat(4,1fr)'}
function resolvePage(...ids){for(const id of ids){if(document.getElementById(id)||document.querySelector(`[data-go="${id}"]`))return id}return ids[0]}
function openPage(...ids){const id=resolvePage(...ids),b=document.querySelector(`[data-go="${id}"]`);if(b){b.click();return}location.hash='#'+id}
function voice(){const old=document.getElementById('voiceCore');if(old){old.click();return}openPage('ai')}
function render(){hideLegacy();let root=document.getElementById('aiOffice');if(!root){root=document.createElement('section');root.id='aiOffice';const home=document.getElementById('home');(home||document.querySelector('main')||document.body).prepend(root)}const now=dateParts(),asof=cutoff();root.innerHTML=`
<div class="ups-head"><div class="ups-logo">UP<em>’S</em><small>AI COMMAND</small></div><div class="ups-icons"><div class="ups-icon" aria-label="通知">♢</div><div class="ups-icon" aria-label="メニュー">☰</div></div></div>
<div class="ups-greet"><div class="hello">こんにちは</div><h1>アップズ君</h1><p>話すだけで、すべての業務をサポートします。<br>配送・売上・人材・営業・経理・AI事業まで、なんでも聞いてください。</p><div class="ups-month">▣ ${now.y}年${now.m}月</div></div>
<div class="ups-core-zone"><div class="ups-orbit"><div class="ups-sweep"></div></div><button class="ups-core ${chatBusy?'busy':''}" type="button" aria-label="アップズ君に話しかける"><div><b>UP’S AI</b><div class="ups-wave"></div><small>${chatBusy?'PROCESSING':'STANDBY'}</small></div></button><button class="ups-talk" type="button"><span>🎙</span><div>アップズ君に話しかける<small>はい、アップズ君</small></div></button></div>
<div class="ups-kpis"><div class="ups-kpi"><span>▥ 今月売上</span><b>${yen(finance?.monthRevenue)}</b><small>${asof}</small></div><div class="ups-kpi gross"><span>● 確認済み粗利</span><b>${yen(finance?.confirmedGrossProfit)}</b><small>${asof}</small></div><div class="ups-kpi dr"><span>♟ DR支払</span><b>${yen(finance?.monthDriverCost)}</b><small>${asof}</small></div><div class="ups-kpi today"><span>▣ 今日の売上</span><b>${yen(finance?.todayRevenue)}</b><small>${now.m}/${now.d}</small></div></div>
<div class="ups-menu"><button data-ups-go="ops"><div class="ico">▣</div><b>配送・シフト</b><small>出勤・欠車・現場管理</small></button><button data-ups-go="sales"><div class="ico">▥</div><b>売上・利益</b><small>拠点別の実績確認</small></button><button data-ups-go="drivers"><div class="ico">♧</div><b>ドライバー</b><small>台帳・稼働・評価</small></button><button data-ups-go="jobs"><div class="ico">⊕</div><b>採用・求人</b><small>応募管理・面接</small></button><button data-ups-go="market"><div class="ico">✉</div><b>営業リスト</b><small>メール・電話・商談</small></button><button data-ups-go="business"><div class="ico">◯</div><b>AI事業</b><small>SNS・note・収益化</small></button></div>
<div class="ups-note">重要情報や確認事項はここだけに表示します。中央のAIは1つに統一し、質問内容に応じて経理・配送・営業・採用・分析などの専門機能へ内部で自動振り分けします。</div>
<div class="ups-footer"><span>UP'S AI // ${VERSION}</span><span>${chatBusy?'VOICE / CHAT ACTIVE':'SYSTEM STANDBY'}</span></div>`;
root.querySelector('.ups-core').onclick=voice;root.querySelector('.ups-talk').onclick=voice;root.querySelectorAll('[data-ups-go]').forEach(b=>b.onclick=()=>{const k=b.dataset.upsGo;if(k==='ops')openPage('ops','shift','delivery');else if(k==='sales')openPage('sales');else if(k==='drivers')openPage('drivers','people');else if(k==='jobs')openPage('jobs','people');else if(k==='market')openPage('market');else if(k==='business')openPage('market','ai')})}
async function loadFinance(){try{const r=await fetch('./finance-status.json?v='+Date.now(),{cache:'no-store'});if(r.ok)finance=await r.json()}catch(e){}render()}
window.addEventListener('ups-chat-busy',e=>{chatBusy=!!e.detail;render()});css();render();loadFinance();setInterval(loadFinance,60000);
})();