(()=>{
  const VERSION='V7.0.26';
  const STATUS={active:['稼働中','🟢'],analysis:['分析中','🔵'],approval:['承認待ち','🟡'],idle:['待機','⚪'],alert:['要確認','🔴']};
  const employees=[
    {id:'ceo',dept:'AI社長室',name:'アップズ君',role:'統括AI',icon:'◉',status:'idle',task:'全社状況を監視中'},
    {id:'accounting',dept:'AI経理部',name:'Aさん',role:'売上・粗利・請求確認',icon:'A',status:'analysis',task:'売上・粗利データを確認'},
    {id:'shift',dept:'配送管理部',name:'Bさん',role:'シフト・欠車・稼働管理',icon:'B',status:'idle',task:'シフトと稼働状況を監視'},
    {id:'sales',dept:'AI営業部',name:'Cさん',role:'営業候補・商談フォロー',icon:'C',status:'idle',task:'営業案件の待機中'},
    {id:'jobs',dept:'AI採用部',name:'Dさん',role:'求人改善・応募分析',icon:'D',status:'idle',task:'求人・応募状況を監視'},
    {id:'monetization',dept:'AI事業部',name:'Eさん',role:'note・SNS・商品企画',icon:'E',status:'idle',task:'収益化タスクの待機中'},
    {id:'profit',dept:'AI分析部',name:'Fさん',role:'拠点別利益・稼働率分析',icon:'F',status:'analysis',task:'経営数値を分析'}
  ];
  let finance=null,chatBusy=false;
  function css(){if(document.getElementById('ai-office-style'))return;const s=document.createElement('style');s.id='ai-office-style';s.textContent=`.aio-wrap{margin:18px 0;padding:18px;border:1px solid #1e5666;border-radius:20px;background:linear-gradient(180deg,#07131dcc,#03090fcc);box-shadow:inset 0 0 35px #0fcfff0c}.aio-head{display:flex;justify-content:space-between;gap:12px;align-items:center;flex-wrap:wrap}.aio-title{font-size:18px;font-weight:900;letter-spacing:.08em;color:#dffbff}.aio-sub{font-size:11px;color:#78aeb9}.aio-summary{display:flex;gap:8px;flex-wrap:wrap}.aio-chip{font-size:11px;border:1px solid #245463;border-radius:999px;padding:6px 9px;color:#a7dce6;background:#06141d}.aio-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin-top:15px}.aio-card{position:relative;min-width:0;border:1px solid #173e4a;border-radius:16px;padding:13px;background:#051018;cursor:pointer;transition:.2s}.aio-card:hover{border-color:#388ca2;transform:translateY(-1px)}.aio-top{display:flex;align-items:center;gap:10px}.aio-avatar{width:42px;height:42px;border-radius:50%;display:grid;place-items:center;border:1px solid #386a78;background:#08202b;font-weight:900;color:#9bf5ff}.aio-name{font-size:14px;font-weight:900;color:#e7fbff}.aio-dept{font-size:10px;color:#75a5af}.aio-status{margin-top:10px;font-size:11px;font-weight:800}.aio-task{margin-top:7px;color:#9ec3cb;font-size:11px;line-height:1.45;min-height:32px}.aio-detail{display:none;margin-top:10px;padding-top:10px;border-top:1px solid #12323c;font-size:11px;color:#c5e6ec;line-height:1.6}.aio-card.open .aio-detail{display:block}.aio-line{height:2px;background:linear-gradient(90deg,transparent,#35d5ff66,transparent);margin:14px 0 0;animation:aioPulse 2.4s ease-in-out infinite}@keyframes aioPulse{50%{opacity:.25}}@media(max-width:900px){.aio-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:480px){.aio-grid{grid-template-columns:1fr}.aio-wrap{padding:14px}}`;document.head.appendChild(s)}
  function calc(){const q=Array.isArray(finance?.approvalQueue)?finance.approvalQueue.length:0;const unknown=Number(finance?.unknownCount||0);const ceo=employees.find(x=>x.id==='ceo');ceo.status=chatBusy?'active':q>0?'approval':'idle';ceo.task=chatBusy?'ユーザーと会話・指示処理中':q>0?`${q}件の承認待ちを管理`:'全社状況を監視中';const a=employees.find(x=>x.id==='accounting');a.status=unknown>0?'alert':'analysis';a.task=unknown>0?`未確認データ ${unknown}件を確認中`:'売上・粗利データを分析';const p=employees.find(x=>x.id==='profit');p.status='analysis';p.task=finance?.monthRevenue?`今月売上 ¥${Number(finance.monthRevenue).toLocaleString()} を分析`:'経営数値を分析'}
  function render(){calc();let root=document.getElementById('aiOffice');if(!root){root=document.createElement('section');root.id='aiOffice';root.className='aio-wrap';const target=document.querySelector('main')||document.querySelector('.main')||document.body;const core=document.querySelector('.ups-core-shell');if(core&&core.parentElement)core.parentElement.insertBefore(root,core.nextSibling);else target.prepend(root)}const counts={active:0,analysis:0,approval:0,idle:0,alert:0};employees.forEach(e=>counts[e.status]++);root.innerHTML=`<div class="aio-head"><div><div class="aio-title">AI OFFICE</div><div class="aio-sub">UP’s AI ORGANIZATION / ${VERSION}</div></div><div class="aio-summary"><span class="aio-chip">稼働 ${counts.active}</span><span class="aio-chip">分析 ${counts.analysis}</span><span class="aio-chip">承認 ${counts.approval}</span><span class="aio-chip">要確認 ${counts.alert}</span></div></div><div class="aio-grid">${employees.map(e=>{const [txt,dot]=STATUS[e.status];return `<article class="aio-card" data-id="${e.id}" tabindex="0"><div class="aio-top"><div class="aio-avatar">${e.icon}</div><div><div class="aio-name">${e.name}</div><div class="aio-dept">${e.dept}</div></div></div><div class="aio-status">${dot} ${txt}</div><div class="aio-task">${e.task}</div><div class="aio-detail"><b>${e.role}</b><br>現在: ${e.task}<br>${e.id==='ceo'?'各部署の状態・承認・優先順位を統括します。':'実際のタスク処理時のみ稼働状態に切り替わります。'}</div></article>`}).join('')}</div><div class="aio-line"></div>`;root.querySelectorAll('.aio-card').forEach(c=>{const toggle=()=>c.classList.toggle('open');c.addEventListener('click',toggle);c.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();toggle()}})})}
  async function loadFinance(){try{const r=await fetch('./finance-status.json?aio='+Date.now(),{cache:'no-store'});if(r.ok)finance=await r.json()}catch(e){}render()}
  window.addEventListener('ups-chat-busy',e=>{chatBusy=!!e.detail;render()});
  css();render();loadFinance();setInterval(loadFinance,60000);
})();