(()=>{
  const VERSION='V7.1.0';
  const WAKE_WORDS=['アップズ君','アップズくん','アップス君','アップスくん','ups君'];
  const SR=window.SpeechRecognition||window.webkitSpeechRecognition;
  let armed=false,wakeRec=null,followRec=null,speaking=false,following=false,chatBusy=false;
  function injectStyles(){if(document.getElementById('ups-ai-core-style'))return;const s=document.createElement('style');s.id='ups-ai-core-style';s.textContent=`.ups-core-shell{position:relative;display:grid;place-items:center;min-height:280px;padding:18px 0 12px;isolation:isolate}.ups-ring,.ups-ring2,.ups-ring3{position:absolute;border-radius:50%;pointer-events:none}.ups-ring{width:240px;height:240px;border:1px solid #66ebff55;animation:upsSpin 12s linear infinite}.ups-ring2{width:286px;height:286px;border:1px dashed #59cdff33;animation:upsSpinR 19s linear infinite}.ups-ring3{width:324px;height:324px;border:1px solid #4896be22}#voiceCore.ups-core{position:relative;width:190px!important;height:190px!important;border-radius:50%!important;border:1px solid #78f1ffc7!important;background:radial-gradient(circle,#8effff 0 2%,#28d4ef 3% 7%,#0e6f8a 8% 18%,#073347 19% 38%,#020b13 39% 100%)!important;box-shadow:0 0 25px #48e0ff88,0 0 70px #2acdff38!important;color:#effdff!important;display:grid!important;place-items:center!important;padding:0!important;cursor:pointer;animation:upsIdle 3s ease-in-out infinite}.ups-core-center{text-align:center;display:flex;flex-direction:column;align-items:center;gap:7px}.ups-core-dot{width:18px;height:18px;border-radius:50%;background:#b8ffff;box-shadow:0 0 20px #34dcff}.ups-core-name{font-size:18px;font-weight:900;letter-spacing:.16em}.ups-core-state{font-size:9px;color:#8edfed;font-weight:800;letter-spacing:.12em}#voiceCore.ups-core.ups-listening{box-shadow:0 0 35px #73ffd7e6,0 0 100px #37ffcd66!important;animation:upsListen .7s ease-in-out infinite alternate}#voiceCore.ups-core.ups-thinking{box-shadow:0 0 35px #5ca8ffd9,0 0 100px #466cff55!important}#voiceCore.ups-core.ups-speaking{box-shadow:0 0 38px #76ffd8f2,0 0 110px #34ffc355!important}.ups-voice-caption{text-align:center;color:#79bfd0;font-size:10px;margin-top:10px;line-height:1.6}.ups-voice-caption b{color:#aef8ff}@keyframes upsSpin{to{transform:rotate(360deg)}}@keyframes upsSpinR{to{transform:rotate(-360deg)}}@keyframes upsIdle{50%{filter:brightness(1.15);transform:scale(1.015)}}@keyframes upsListen{to{filter:brightness(1.35);transform:scale(1.05)}}@media(max-width:900px){.ups-core-shell{min-height:250px}.ups-ring{width:215px;height:215px}.ups-ring2{width:252px;height:252px}.ups-ring3{width:282px;height:282px}#voiceCore.ups-core{width:170px!important;height:170px!important}}`;document.head.appendChild(s)}
  function setState(state,label){const c=document.getElementById('voiceCore');if(!c)return;c.classList.remove('ups-listening','ups-thinking','ups-speaking');if(state)c.classList.add('ups-'+state);const x=c.querySelector('.ups-core-state');if(x)x.textContent=label||'ONLINE'}
  function build(){document.title='アップズ君 '+VERSION;const c=document.getElementById('voiceCore');if(!c)return;const p=c.parentElement;if(p&&!p.classList.contains('ups-core-shell')){p.classList.add('ups-core-shell');['ups-ring3','ups-ring2','ups-ring'].forEach(n=>{const r=document.createElement('span');r.className=n;p.insertBefore(r,c)});const cap=document.createElement('div');cap.className='ups-voice-caption';cap.innerHTML='<b>UP’s AI LIVE</b><br>1回タップで自然な音声会話を開始';p.appendChild(cap)}c.classList.add('ups-core');c.innerHTML='<span class="ups-core-center"><span class="ups-core-dot"></span><span class="ups-core-name">UP’S AI</span><span class="ups-core-state">STANDBY</span></span>';c.setAttribute('aria-label','アップズ君 LIVE音声会話を開始')}
  function hasWake(t){return WAKE_WORDS.some(w=>(t||'').toLowerCase().includes(w.toLowerCase()))}
  function stripWake(t){let x=(t||'').trim();WAKE_WORDS.forEach(w=>x=x.replace(new RegExp(w,'gi'),'').trim());return x.replace(/^[、,。\s]+/,'').trim()}
  function stop(rec){try{rec&&rec.stop()}catch(e){}}
  function bestVoice(){try{const vs=speechSynthesis.getVoices().filter(v=>/^ja/i.test(v.lang||'')||/Japanese|日本語/i.test(v.name||''));const pref=['Kyoko','Otoya','Nanami','Haruka','Ayumi','Google 日本語','Google Japanese'];return vs.sort((a,b)=>{const s=v=>pref.reduce((n,p,i)=>n+((v.name||'').toLowerCase().includes(p.toLowerCase())?100-i:0),0)+(v.localService?10:0);return s(b)-s(a)})[0]||null}catch{return null}}
  function localSpeak(text,after){if(!('speechSynthesis'in window)){after&&after();return}try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='ja-JP';u.rate=.96;u.pitch=1.02;const v=bestVoice();if(v)u.voice=v;speaking=true;u.onstart=()=>setState('speaking','RESPONDING');const done=()=>{speaking=false;after&&after()};u.onend=done;u.onerror=done;speechSynthesis.speak(u)}catch(e){speaking=false;after&&after()}}
  async function ask(message){message=String(message||'').trim();if(!message||chatBusy)return;following=false;stop(wakeRec);stop(followRec);setState('thinking','THINKING');if(typeof window.upsChat==='function'){await window.upsChat(message,{voice:true});return}if(typeof window.go==='function'){await window.go(message);return}setState(null,'CHAT OFFLINE')}
  function followUp(){if(!SR||!armed||speaking||chatBusy||document.hidden)return;following=true;stop(wakeRec);followRec=new SR();followRec.lang='ja-JP';followRec.continuous=false;followRec.interimResults=false;let got=false;followRec.onstart=()=>setState('listening','YOUR TURN');followRec.onresult=e=>{got=true;const t=e.results?.[0]?.[0]?.transcript||'';if(t)ask(t)};followRec.onerror=e=>{following=false;if(e.error!=='aborted')restartWake()};followRec.onend=()=>{if(!got){following=false;restartWake()}};setTimeout(()=>{try{followRec.start()}catch(e){following=false;restartWake()}},260)}
  function wakeDetected(text){const cmd=stripWake(text);stop(wakeRec);if(cmd){ask(cmd);return}setState('listening','YES?');localSpeak('はい、どうぞ',()=>followUp())}
  function restartWake(){if(!armed||speaking||following||chatBusy||document.hidden)return;setTimeout(()=>{try{wakeRec&&wakeRec.start()}catch(e){}},420)}
  function startWake(){if(!SR){setState(null,'VOICE UNSUPPORTED');return}armed=true;following=false;if(!wakeRec){wakeRec=new SR();wakeRec.lang='ja-JP';wakeRec.continuous=true;wakeRec.interimResults=false;wakeRec.onstart=()=>setState(null,'VOICE READY');wakeRec.onresult=e=>{if(speaking||following||chatBusy)return;for(let i=e.resultIndex;i<e.results.length;i++){if(e.results[i].isFinal){const t=e.results[i][0].transcript||'';if(hasWake(t)){wakeDetected(t);break}}}};wakeRec.onerror=e=>{if(e.error==='not-allowed'||e.error==='service-not-allowed'){armed=false;setState(null,'MIC BLOCKED')}};wakeRec.onend=()=>restartWake()}try{wakeRec.start()}catch(e){restartWake()}}
  async function startPreferredVoice(){if(typeof window.upsLiveStart==='function'){setState('thinking','CONNECTING');const ok=await window.upsLiveStart();if(ok){armed=false;stop(wakeRec);stop(followRec);setState('listening','LIVE');return}}startWake()}
  window.addEventListener('ups-chat-busy',e=>{chatBusy=!!e.detail;if(chatBusy)setState('thinking','THINKING')});
  window.addEventListener('ups-speech-start',()=>{speaking=true;stop(wakeRec);stop(followRec);setState('speaking','RESPONDING')});
  window.addEventListener('ups-speech-end',()=>{speaking=false;if(armed)setTimeout(followUp,320);else setState(null,'STANDBY')});
  window.addEventListener('ups-chat-error',()=>{chatBusy=false;setState(null,'VOICE READY');restartWake()});
  window.addEventListener('ups-live-state',e=>{const st=e.detail?.state,label=e.detail?.label;if(st==='listening')setState('listening',label||'LIVE');else if(st==='speaking')setState('speaking',label||'SPEAKING');else if(st==='connecting')setState('thinking',label||'CONNECTING');else if(st==='idle')setState(null,label||'STANDBY')});
  function init(){injectStyles();build();const c=document.getElementById('voiceCore');if(!c)return;c.onclick=e=>{e.preventDefault();e.stopPropagation();startPreferredVoice()};const mic=document.getElementById('mic');if(mic)mic.onclick=e=>{e.preventDefault();e.stopPropagation();startPreferredVoice()};document.addEventListener('visibilitychange',()=>{if(document.hidden){stop(wakeRec);stop(followRec)}else if(!window.upsLiveConnected?.())restartWake()});const st=document.getElementById('status');if(st)st.textContent='UP’s AI READY'}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();