(()=>{
  const VERSION='V7.0.24';
  const WAKE_WORDS=['アップズ君','アップズくん','アップス君','アップスくん','ups君'];
  const SR=window.SpeechRecognition||window.webkitSpeechRecognition;
  let armed=false,wakeRec=null,commandRec=null,speaking=false,waitingCommand=false;

  function injectStyles(){
    if(document.getElementById('ups-ai-core-style'))return;
    const s=document.createElement('style');s.id='ups-ai-core-style';s.textContent=`
    .ups-core-shell{position:relative;display:grid;place-items:center;min-height:280px;padding:18px 0 12px;isolation:isolate}.ups-ring,.ups-ring2,.ups-ring3{position:absolute;border-radius:50%;pointer-events:none}.ups-ring{width:240px;height:240px;border:1px solid #66ebff55;animation:upsSpin 12s linear infinite}.ups-ring2{width:286px;height:286px;border:1px dashed #59cdff33;animation:upsSpinR 19s linear infinite}.ups-ring3{width:324px;height:324px;border:1px solid #4896be22}#voiceCore.ups-core{position:relative;width:190px!important;height:190px!important;border-radius:50%!important;border:1px solid #78f1ffc7!important;background:radial-gradient(circle,#8effff 0 2%,#28d4ef 3% 7%,#0e6f8a 8% 18%,#073347 19% 38%,#020b13 39% 100%)!important;box-shadow:0 0 25px #48e0ff88,0 0 70px #2acdff38!important;color:#effdff!important;display:grid!important;place-items:center!important;padding:0!important;cursor:pointer;animation:upsIdle 3s ease-in-out infinite}.ups-core-center{text-align:center;display:flex;flex-direction:column;align-items:center;gap:7px}.ups-core-dot{width:18px;height:18px;border-radius:50%;background:#b8ffff;box-shadow:0 0 20px #34dcff}.ups-core-name{font-size:18px;font-weight:900;letter-spacing:.16em}.ups-core-state{font-size:9px;color:#8edfed;font-weight:800;letter-spacing:.12em}#voiceCore.ups-core.ups-listening{box-shadow:0 0 35px #73ffd7e6,0 0 100px #37ffcd66!important;animation:upsListen .7s ease-in-out infinite alternate}#voiceCore.ups-core.ups-thinking{box-shadow:0 0 35px #5ca8ffd9,0 0 100px #466cff55!important}#voiceCore.ups-core.ups-speaking{box-shadow:0 0 38px #76ffd8f2,0 0 110px #34ffc355!important}.ups-voice-caption{text-align:center;color:#79bfd0;font-size:10px;margin-top:10px;line-height:1.6}.ups-voice-caption b{color:#aef8ff}@keyframes upsSpin{to{transform:rotate(360deg)}}@keyframes upsSpinR{to{transform:rotate(-360deg)}}@keyframes upsIdle{50%{filter:brightness(1.15);transform:scale(1.015)}}@keyframes upsListen{to{filter:brightness(1.35);transform:scale(1.05)}}@media(max-width:900px){.ups-core-shell{min-height:250px}.ups-ring{width:215px;height:215px}.ups-ring2{width:252px;height:252px}.ups-ring3{width:282px;height:282px}#voiceCore.ups-core{width:170px!important;height:170px!important}}
    `;document.head.appendChild(s);
  }
  function setState(state,label){const c=document.getElementById('voiceCore');if(!c)return;c.classList.remove('ups-listening','ups-thinking','ups-speaking');if(state)c.classList.add('ups-'+state);const x=c.querySelector('.ups-core-state');if(x)x.textContent=label||'ONLINE'}
  function build(){document.title='アップズ君 '+VERSION;const c=document.getElementById('voiceCore');if(!c)return;const p=c.parentElement;if(p&&!p.classList.contains('ups-core-shell')){p.classList.add('ups-core-shell');['ups-ring3','ups-ring2','ups-ring'].forEach(n=>{const r=document.createElement('span');r.className=n;p.insertBefore(r,c)});const cap=document.createElement('div');cap.className='ups-voice-caption';cap.innerHTML='<b>UP’s AI CORE</b><br>一度起動後「アップズ君」で会話';p.appendChild(cap)}c.classList.add('ups-core');c.innerHTML='<span class="ups-core-center"><span class="ups-core-dot"></span><span class="ups-core-name">UP’S AI</span><span class="ups-core-state">STANDBY</span></span>';c.setAttribute('aria-label','アップズ君 音声会話を開始')}
  function hasWake(t){return WAKE_WORDS.some(w=>(t||'').toLowerCase().includes(w.toLowerCase()))}
  function stripWake(t){let x=(t||'').trim();WAKE_WORDS.forEach(w=>x=x.replace(new RegExp(w,'gi'),'').trim());return x.replace(/^[、,。\s]+/,'').trim()}
  function stopWake(){try{wakeRec&&wakeRec.stop()}catch(e){}}
  function speak(text,after){if(!('speechSynthesis'in window)){after&&after();return}try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='ja-JP';u.rate=1.04;speaking=true;u.onstart=()=>setState('speaking','RESPONDING');u.onend=()=>{speaking=false;after&&after()};u.onerror=()=>{speaking=false;after&&after()};speechSynthesis.speak(u)}catch(e){speaking=false;after&&after()}}
  async function askAI(message){if(!message)return;waitingCommand=false;setState('thinking','THINKING');try{let previousResponseId='';try{previousResponseId=localStorage.getItem('ups_previous_response_id')||''}catch(e){}const r=await fetch('https://jarvis-api.t-ups2024.workers.dev/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message,previousResponseId})});const j=await r.json();if(!r.ok||!j.success)throw new Error(j.error||'AI error');try{if(j.responseId)localStorage.setItem('ups_previous_response_id',j.responseId)}catch(e){}const log=document.getElementById('chatlog');if(log){const u=document.createElement('div');u.className='msg me';u.textContent=message;log.appendChild(u);const a=document.createElement('div');a.className='msg ai';a.textContent=j.reply;log.appendChild(a);log.scrollTop=log.scrollHeight}speak(j.reply,()=>{setState(null,'VOICE READY');restartWake()})}catch(e){setState(null,'AI ERROR');speak('通信を確認してください',()=>restartWake())}}
  function listenForCommand(){if(!SR)return;waitingCommand=true;stopWake();setState('listening','LISTENING');commandRec=new SR();commandRec.lang='ja-JP';commandRec.continuous=false;commandRec.interimResults=false;let got=false;commandRec.onresult=e=>{got=true;const t=e.results?.[0]?.[0]?.transcript||'';if(t)askAI(t)};commandRec.onerror=()=>{waitingCommand=false;setState(null,'VOICE READY');restartWake()};commandRec.onend=()=>{if(!got&&waitingCommand){waitingCommand=false;setState(null,'VOICE READY');restartWake()}};setTimeout(()=>{try{commandRec.start()}catch(e){waitingCommand=false;restartWake()}},250)}
  function wakeDetected(text){const cmd=stripWake(text);stopWake();if(cmd){askAI(cmd);return}setState('listening','YES?');speak('はい',()=>{setState('listening','LISTENING');listenForCommand()})}
  function restartWake(){if(!armed||speaking||waitingCommand||document.hidden)return;setTimeout(()=>{try{wakeRec&&wakeRec.start()}catch(e){}},500)}
  function startWake(){if(!SR){setState(null,'VOICE UNSUPPORTED');return}armed=true;if(!wakeRec){wakeRec=new SR();wakeRec.lang='ja-JP';wakeRec.continuous=true;wakeRec.interimResults=false;wakeRec.onstart=()=>setState(null,'VOICE READY');wakeRec.onresult=e=>{if(speaking||waitingCommand)return;for(let i=e.resultIndex;i<e.results.length;i++){if(e.results[i].isFinal){const t=e.results[i][0].transcript||'';if(hasWake(t)){wakeDetected(t);break}}}};wakeRec.onerror=e=>{if(e.error==='not-allowed'||e.error==='service-not-allowed'){armed=false;setState(null,'MIC BLOCKED')}};wakeRec.onend=()=>restartWake()}try{wakeRec.start()}catch(e){restartWake()}}
  function init(){injectStyles();build();const c=document.getElementById('voiceCore');if(!c)return;c.onclick=e=>{e.preventDefault();e.stopPropagation();startWake()};const mic=document.getElementById('mic');if(mic)mic.onclick=e=>{e.preventDefault();startWake()};document.addEventListener('visibilitychange',()=>{if(document.hidden){try{wakeRec&&wakeRec.stop()}catch(e){}}else restartWake()});const st=document.getElementById('status');if(st)st.textContent='UP’s AI READY'}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();